patterns:
  - type: cycle
    instances: 3
    accounts_per_cycle: 4
    amount: 2500
    currency: "USD"
    start_date: "2025-01-01"
    end_date: "2025-01-10"
    label: true

  - type: scatter_gather
    instances: 2
    sources: 1
    intermediates: 3
    sinks: 1
    total_amount: 5000
    currency: "USD"
    start_date: "2025-01-11"
    end_date: "2025-01-20"
    label: true
