patterns:
  - type: fan_in
    instances: 5
    sources_per_target: 5         # 5 sources funneling to 1 target
    amount_per_source: 200        # Each sends $200
    currency: "USD"
    start_date: "2025-01-01"
    end_date: "2025-01-03"
    label: true

  - type: scatter_gather
    instances: 2
    sources: 4
    intermediates: 2
    sinks: 1
    total_amount: 1000
    currency: "USD"
    start_date: "2025-01-04"
    end_date: "2025-01-06"
    label: true

defaults:
  currency: USD
  label: true